export const WOLRD_WIDTH = 2600
export const WORLD_HEIGHT = 800
export const TOGGLE_SINGLE_PAGE_TRANSITION_DELAY = 75
export const TOGGLE_SINGLE_PAGE_TRANSITION_REF_DURATION = 1200
export const BLUR_ITERATIONS = 8

export const PREVIEW_PHOTO_REF_WIDTH = 300 * 1.15
export const PREVIEW_PHOTO_REF_HEIGHT = 450 * 1.15

export const CAMERA_MIN_VELOCITY_TO_BE_MOVING = 1.25
export const EVT_CAMERA_HANDLE_MOVEMENT_WORLD = 'EVT_CAMERA_HANDLE_MOVEMENT_WORLD'
export const EVT_CAMERA_ZOOM_OUT_DRAG_START = 'EVT_CAMERA_ZOOM_OUT_DRAG_START'
export const EVT_CAMERA_ZOOM_IN_DRAG_END = 'EVT_CAMERA_ZOOM_IN_DRAG_END'

export const EVT_LOADED_PROJECTS = 'EVT_LOADED_PROJECTS'

export const EVT_OPEN_REQUEST_SINGLE_PROJECT = 'EVT_OPEN_REQUEST_SINGLE_PROJECT'
export const EVT_OPENING_SINGLE_PROJECT = 'EVT_OPENING_SINGLE_PROJECT'
export const EVT_OPEN_SINGLE_PROJECT = 'EVT_OPEN_SINGLE_PROJECT'

export const EVT_CLOSE_REQUEST_SINGLE_PROJECT = 'EVT_CLOSE_REQUEST_SINGLE_PROJECT'
export const EVT_CLOSE_SINGLE_PROJECT = 'EVT_CLOSE_SINGLE_PROJECT'
export const EVT_CLOSING_SINGLE_PROJECT = 'EVT_CLOSING_SINGLE_PROJECT'

export const EVT_FADE_OUT_SINGLE_VIEW = 'EVT_FADE_OUT_SINGLE_VIEW'
export const EVT_SLIDER_BUTTON_LEFT_CLICK = 'EVT_SLIDER_BUTTON_LEFT_CLICK'
export const EVT_SLIDER_BUTTON_NEXT_CLICK = 'EVT_SLIDER_BUTTON_NEXT_CLICK'
export const EVT_RAF_UPDATE_APP = 'EVT_RAF_UPDATE_APP'
export const EVT_MOUSEMOVE_APP = 'EVT_MOUSEMOVE_APP'

export const EVT_ON_SCENE_DRAG_START = 'EVT_ON_SCENE_DRAG_START'
export const EVT_ON_SCENE_DRAG = 'EVT_ON_SCENE_DRAG'
export const EVT_ON_SCENE_DRAG_END = 'EVT_ON_SCENE_DRAG_END'

export const EVT_HOVER_SINGLE_PROJECT_ENTER = 'EVT_HOVER_SINGLE_PROJECT_ENTER'
export const EVT_HOVER_SINGLE_PROJECT_LEAVE = 'EVT_HOVER_SINGLE_PROJECT_LEAVE'

export const EVT_RENDER_CURSOR_SCENE_FRAME = 'EVT_RENDER_CURSOR_SCENE_FRAME'
export const EVT_RENDER_PHOTO_SCENE_FRAME = 'EVT_RENDER_PHOTO_SCENE_FRAME'
export const EVT_RENDER_PHOTO_POSTFX_FRAME = 'EVT_RENDER_PHOTO_POSTFX_FRAME'

export const EVT_APP_RESIZE = 'EVT_APP_RESIZE'

export const EVT_CLICK_PREV_PROJECT = 'EVT_CLICK_PREV_PROJECT'
export const EVT_CLICK_NEXT_PROJECT = 'EVT_CLICK_NEXT_PROJECT'
export const EVT_TRANSITION_OUT_CURRENT_PRODUCT_PHOTO = 'EVT_TRANSITION_OUT_CURRENT_PRODUCT_PHOTO'
export const EVT_TRANSITION_IN_CURRENT_PRODUCT_PHOTO = 'EVT_TRANSITION_IN_CURRENT_PRODUCT_PHOTO'
export const EVT_NEXT_PROJECT_TRANSITIONED_IN = 'EVT_NEXT_PROJECT_TRANSITIONED_IN'

export const EVT_OPEN_REQUEST_INFO_SECTION = 'EVT_OPEN_REQUEST_INFO_SECTION'
export const EVT_OPENING_INFO_SECTION = 'EVT_OPENING_INFO_SECTION'
