export const WOLRD_WIDTH = 2000
export const WORLD_HEIGHT = 1000

export const EVT_SLIDER_BUTTON_LEFT_CLICK = 'EVT_SLIDER_BUTTON_LEFT_CLICK'
export const EVT_SLIDER_BUTTON_NEXT_CLICK = 'EVT_SLIDER_BUTTON_NEXT_CLICK'
export const EVT_RAF_UPDATE_APP = 'EVT_RAF_UPDATE_APP'
export const EVT_MOUSEMOVE_APP = 'EVT_MOUSEMOVE_APP'
