export const WOLRD_WIDTH = 1700
export const WORLD_HEIGHT = 800

export const EVT_LOADED_PROJECTS = 'EVT_LOADED_PROJECTS'
export const EVT_CLICKED_SINGLE_PROJECT = 'EVT_CLICKED_SINGLE_PROJECT'
export const EVT_FADE_IN_SINGLE_VIEW = 'EVT_FADE_IN_SINGLE_VIEW'
export const EVT_SLIDER_BUTTON_MOUSE_ENTER = 'EVT_SLIDER_BUTTON_MOUSE_ENTER'
export const EVT_SLIDER_BUTTON_MOUSE_LEAVE = 'EVT_SLIDER_BUTTON_MOUSE_LEAVE'
export const EVT_SLIDER_BUTTON_LEFT_CLICK = 'EVT_SLIDER_BUTTON_LEFT_CLICK'
export const EVT_SLIDER_BUTTON_NEXT_CLICK = 'EVT_SLIDER_BUTTON_NEXT_CLICK'
export const EVT_RAF_UPDATE_APP = 'EVT_RAF_UPDATE_APP'
export const EVT_MOUSEMOVE_APP = 'EVT_MOUSEMOVE_APP'
